### ISSUE TITLE
Multiple export tasks

### ISSUE THREAD

**Issue by BartDubois** [jakzal/gradle-structurizr-cli#89]
Hi I get the error when I try to define multiple exports.

```
Reason: Task ':structurizrCliExport-plantuml0' uses this output of task ':structurizrCliExport-plantuml1' without declaring an explicit or implicit dependency
```

The definition in `build.gradle.kt` is
```
structurizrCli {
    version = "1.30.0"
    
    export {
        format = "plantuml"
        workspace = "docs/diagrams/m1/workspace.dsl"
    }

    export {
        format = "plantuml"
        workspace = "docs/diagrams/m2/workspace.dsl"
    }
}
```

**Comment by BartDubois** [comment]
Used version 1.5

**Comment by jakzal** [comment]
Thanks for reporting, I managed to reproduce this in a test case:

```kotlin
class ExportFunctionalTest : FunctionalTest {

    @Test
    fun `it exports multiple workspaces`(@TempDir projectDir: File) {
        givenWorkspace(projectDir, "workspace1.dsl")
        givenWorkspace(projectDir, "workspace2.dsl")
        givenConfiguration(projectDir, """
            plugins {
                id 'pl.zalas.structurizr-cli'
            }
            structurizrCli {
                export {
                    format = "plantuml"
                    workspace = "${projectDir.absolutePath}/workspace1.dsl"
                }
                export {
                    format = "plantuml"
                    workspace = "${projectDir.absolutePath}/workspace2.dsl"
                }
            }
        """)

        execute(projectDir, "structurizrCliExport")

        assertTrue(File("${projectDir.absolutePath}/structurizr-SystemContext.puml").exists())
    }
}
```

```
> Task :structurizrCliDownload
Download https://github.com/structurizr/cli/releases/download/v1.30.0/structurizr-cli-1.30.0.zip

> Task :structurizrCliExtract
Extracted /private/var/folders/jc/t6ywrd5x5nl_pjlzk9txb0j80000gn/T/junit10976781712511694745/build/structurizr-cli/lib/structurizr-cli-1.30.0.jar

> Task :structurizrCliExport-plantuml0
Exporting workspace from /var/folders/jc/t6ywrd5x5nl_pjlzk9txb0j80000gn/T/junit10976781712511694745/workspace1.dsl
 - loading workspace from DSL
 - exporting with StructurizrPlantUMLExporter
 - writing /private/var/folders/jc/t6ywrd5x5nl_pjlzk9txb0j80000gn/T/junit10976781712511694745/structurizr-SystemContext.puml
 - writing /private/var/folders/jc/t6ywrd5x5nl_pjlzk9txb0j80000gn/T/junit10976781712511694745/structurizr-SystemContext-key.puml
 - finished

> Task :structurizrCliExport-plantuml1 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':structurizrCliExport-plantuml1' (type 'Export').
  - Gradle detected a problem with the following location: '/private/var/folders/jc/t6ywrd5x5nl_pjlzk9txb0j80000gn/T/junit10976781712511694745/build/structurizr-cli'.
    
    Reason: Task ':structurizrCliExport-plantuml0' uses this output of task ':structurizrCliExport-plantuml1' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':structurizrCliExport-plantuml1' as an input of ':structurizrCliExport-plantuml0'.
      2. Declare an explicit dependency on ':structurizrCliExport-plantuml1' from ':structurizrCliExport-plantuml0' using Task#dependsOn.
      3. Declare an explicit dependency on ':structurizrCliExport-plantuml1' from ':structurizrCliExport-plantuml0' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/private/var/folders/jc/t6ywrd5x5nl_pjlzk9txb0j80000gn/T/junit10976781712511694745/build/structurizr-cli/lib/structurizr-cli-1.30.0.jar'.
    
    Reason: Task ':structurizrCliExport-plantuml1' uses this output of task ':structurizrCliExport-plantuml0' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':structurizrCliExport-plantuml0' as an input of ':structurizrCliExport-plantuml1'.
      2. Declare an explicit dependency on ':structurizrCliExport-plantuml0' from ':structurizrCliExport-plantuml1' using Task#dependsOn.
      3. Declare an explicit dependency on ':structurizrCliExport-plantuml0' from ':structurizrCliExport-plantuml1' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
4 actionable tasks: 4 executed

Unexpected build execution failure in /var/folders/jc/t6ywrd5x5nl_pjlzk9txb0j80000gn/T/junit10976781712511694745 with arguments [structurizrCliExport]

	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:265)
	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:358)
	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:263)
	at app//pl.zalas.gradle.structurizrcli.FunctionalTest$DefaultImpls.execute(FunctionalTest.kt:55)
	at app//pl.zalas.gradle.structurizrcli.ExportFunctionalTest.execute(ExportFunctionalTest.kt:23)
	at app//pl.zalas.gradle.structurizrcli.FunctionalTest$DefaultImpls.execute$default(FunctionalTest.kt:50)
	at app//pl.zalas.gradle.structurizrcli.ExportFunctionalTest.it exports multiple workspaces(ExportFunctionalTest.kt:65)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.18/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.18/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.18/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.18/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by BartDubois** [comment]
I use Gradle 8.1.1. I'm new in the Gradle tool, but if there is any case I can help you please let me know.

**Comment by jakzal** [comment]
Thanks! I'll definitely need someone to test the fix :)

What I've learnt so far this is already a problem in Gradle 7. Gradle has become more strict in how it handles task dependencies. It treats the output directory where the structurizrCliExport tasks are writing to as a dependency to other structurizrCliExport tasks. That's why it works for one export definition but not for many. This used to work before Gradle 7, but I had no test verifying this behaviour.

Going forward, I need to not only fix the above problem, but also provide a way to configure separate output directories for each export task. Otherwise they might overwrite each other's exports.

**Comment by BartDubois** [comment]
In my config its generated files to the location where the workspace file was. I have two separate directories so no issues on my side. But I can imagine that others can have multiples workspaces in one folder.

**Comment by jakzal** [comment]
I guess most people will use separate directories, or a single namespace, so it might be an edge case.

I released the fix for the problem you reported as [1.5.1](https://github.com/jakzal/gradle-structurizr-cli/releases/tag/1.5.1).

I will take care of the directory configuration when time permits ;)

**Comment by BartDubois** [comment]
Ok I will check if it works and let you know.

**Comment by BartDubois** [comment]
Great it works!
